---
swagger: "2.0"
info:
  description: "API to invoke the execution of the decision service operation DefinirUnidade."
  version: "1.0.0"
  title: "DefinirUnidade API"
  x-ibm-name: "definirunidade-api"
host: "ppsa-br-odm.bpm.ibmcloud.com"
basePath: "/odm/dev/DecisionService/rest"
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
security:
- basicAuthentication: []
paths:
  /AgendarExameService/1.0/DefinirUnidade/1.0:
    post:
      summary: "Invokes the execution of the decision service operation DefinirUnidade."
      description: "Executes the decision service operation DefinirUnidade with the\
        \ path /AgendarExameService/1.0/DefinirUnidade/1.0."
      operationId: "callDefinirUnidadeDecisionServiceOperation"
      parameters:
      - in: "body"
        name: "Request"
        description: "Request for the execution of the decision service operation.\
          \ Contains notably the input parameters that are used for the execution."
        required: true
        schema:
          $ref: "#/definitions/Request"
      responses:
        200:
          description: "Response for the execution of the decision service operation.\
            \ Contains notably the output parameters that are returned by the execution."
          schema:
            $ref: "#/definitions/Response"
        default:
          description: "Error occurring when invoking the execution of the decision\
            \ service operation."
          schema:
            $ref: "#/definitions/Error"
securityDefinitions:
  basicAuthentication:
    description: "HTTP Basic Authentication. Works over HTTP and HTTPS."
    type: "basic"
definitions:
  Response:
    type: "object"
    properties:
      __DecisionID__:
        type: "string"
        description: "Unique identifier representing the execution of the decision\
          \ service operation. If it is not specified, it will be computed automatically."
      agendamento:
        $ref: "#/definitions/Agendamento"
    description: "Response for the execution of the decision service operation. Contains\
      \ notably the output parameters that are returned by the execution."
  Questionario:
    type: "object"
    properties:
      exame:
        type: "string"
      perguntas:
        type: "array"
        items:
          type: "string"
      respostas:
        type: "array"
        items:
          type: "boolean"
  Agendamento:
    type: "object"
    properties:
      unidadesDisponiveis:
        type: "array"
        items:
          type: "string"
  Request:
    type: "object"
    properties:
      __DecisionID__:
        type: "string"
        description: "Unique identifier representing the execution of the decision\
          \ service operation. If it is not specified, it will be computed automatically."
      questionario:
        $ref: "#/definitions/Questionario"
    description: "Request for the execution of the decision service operation. Contains\
      \ notably the input parameters that are used for the execution."
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
        description: "HTTP error code."
      message:
        type: "string"
        description: "Error message."
      details:
        type: "string"
        description: "Detailed error message."
      errorCode:
        type: "string"
        description: "Product error code."
    description: "Error occurring when invoking the execution of the decision service\
      \ operation."
x-ibm-configuration:
  enforced: true
  testable: true
  phase: "realized"
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        title: "invoke"
        timeout: 60
        verb: "POST"
        cache-response: "protocol"
        cache-ttl: 900
        stop-on-error:
        - null
        version: "1.0.0"
        target-url: "https://ppsa-br-odm.bpm.ibmcloud.com/odm/dev/DecisionService/rest/v1/AgendarExameService/1.0/DefinirUnidade/1.0"
        username: "luiz.yanai@scalait.com"
        password: "Corinthians@1910"
    catch: []
